version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./dockerconf
      dockerfile: Dockerfile
    image: "backend"
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./dockerconf/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - ./:/var/www
      - ./dockerconf/nginx.app.conf:/etc/nginx/conf.d/app.conf
